All: Fix invalid URLs in sitemap
https://github.com/jquery/jquerymobile.com/actions/runs/6490030580/job/17625221359

```
DEBUG:scrapy.core.engine:Crawled (200) <GET https://api.jquerymobile.com/wp-sitemap.xml> (referer: None)
ERROR:scrapy.core.scraper:Spider error processing <GET https://api.jquerymobile.com/wp-sitemap.xml> (referer: None)
Traceback (most recent call last):
  …
  File "/home/seleuser/.local/share/virtualenvs/seleuser-AdYDHarm/lib/python3.10/site-packages/scrapy/spiders/sitemap.py"
  in _parse_sitemap
  File "/home/seleuser/.local/share/virtualenvs/seleuser-AdYDHarm/lib/python3.10/site-packages/scrapy/http/request/__init__.py"
  in self._set_url(url)
  File "/home/seleuser/.local/share/virtualenvs/seleuser-AdYDHarm/lib/python3.10/site-packages/scrapy/http/request/__init__.py"
  in _set_url
ValueError: Missing scheme in request url: //api.jquerymobile.com/wp-sitemap-posts-post-1.xml
2023-10-12 01:21:37 [scrapy.core.scraper] ERROR: Spider error processing <GET https://api.jquerymobile.com/wp-sitemap.xml> (referer: None)
```

Ref https://github.com/jquery/infrastructure-puppet/issues/33